### ISSUE TITLE
Geographiccraft incompatibility

### ISSUE THREAD

**Issue by WolfieWaffle** [Prospector/Traverse-Forge#45]
Maybe I'm just doing the configs wrong, but I can't seem to get Traverse biomes generating in a world affected by Geographiccraft/Climate Control. Does anyone know why this is?

**Comment by Frostnox** [comment]
Traverse is compatible with Geographiccraft. Just list all of the biome names in the config under externalBiomeNames. List should look something like: badlands, desert_shrubland, meadow, and so on. Geographiccraft will generate the biome IDs in the config if you run the game, but you will have to manually set the other parameters like incidence, climate, and villages. You should also double check the generated IDs to make sure they are the ones actually used by the corresponding biome. If you need to get the biome names, mods such as CraftTweaker have in-game commands for that. NEI also has a feature that dumps the biome names along with the IDs if you need those too.

**Comment by Prospector** [comment]
^^ good to know
