### ISSUE TITLE
Change model on door

### ISSUE THREAD

**Issue by IronPiston** [Prospector/Traverse-Forge#47]
I'd like to change the door item model in a resource pack so that it renders as it does in the world, but I can't find the door in the assets/traverse/models folder. How would I change the model on the Fir Door item?

**Comment by coderbot16** [comment]
Traverse uses ShootingStar which does resources in code instead of with asset jsons, but you could probably copy the vanilla door model and put it over where the traverse one may be... not exactly sure what the path would be, but I imagine it would be something like `models/block/fir_door.json`

**Comment by IronPiston** [comment]
I'm actually trying to replace the fir door item (the one in your inventory) with a model, but placing a json in both the item and block folder didn't seem to do anything.

**Comment by Prospector** [comment]
Item model is defined in the blockstate file. Point it to your own custom model. I can help you a bit later if you're srill stuck.

**Comment by IronPiston** [comment]
Figured it out, thanks.

If anyone finding this issue later is curious how to do this, the blockstates folder has a folder for door, and inside a file called fir_door.json. On the line that says "inventory": { "model": "traverse:itemblock" },", change the word itemblock to the name of the .json file in the models/block directory.

**Comment by Prospector** [comment]
👍
